apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udxf-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-udxf-api

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udxf-test
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: {{ .Release.Name }}-udxf-test

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-udxf
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ .Release.Name }}-udxf
