# Common values
image:
  repository: udxf-api
  tag: latest
  pullPolicy: IfNotPresent

testImage:
  repository: udxf-test
  tag: latest
  pullPolicy: IfNotPresent
  
mainImage:
  repository: udxf
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "0.5"
    memory: "0.5Gi"

replicaCount: 1

ingress:
  enabled: false
